POST http://localhost:7071/api/http/process-numbers

{
    "number1": 7,
    "number2": 4,
    "userId": "111"
}

### 

GET http://localhost:7071/api/helloWorld1

###

POST http://localhost:7071/api/http/get-data

{
    "userId": ""
}

###

POST http://localhost:7071/api/http/reset-data

{
    "userId": ""
}

###

POST http://localhost:7071/api/http/upload-file/testData.json
Content-Type: application/json

{
    "name": "Test Data"
}

###

GET  http://localhost:7071/api/signalEntityDemo?action=add&amount=2


###

GET  http://localhost:7071/api/signalEntityDemo?action=get

###

GET  http://localhost:7071/api/signalEntityDemo?action=reset
###
POST http://localhost:7071/api/asyncHttpApi/start-orchestrator

{
    "userId": "111"
}


###

POST http://localhost:7071/api/orchestrators/backupSiteContent
Content-Type: application/json

"/Volumes/files/src/azure-functions-sample"


###
POST http://localhost:7071/api/updateDBConcurrentlyDemo