POST http://localhost:7071/api/http/process-numbers

{
    "number1": 7,
    "number2": 4,
    "userId": ""
}

### 

GET http://localhost:7071/api/helloWorld1

###

POST http://localhost:7071/api/http/get-data

{
    "userId": ""
}