POST http://localhost:7071/api/http/process-numbers

{
    "number1": 7,
    "number2": 4,
    "userId": ""
}

### 

GET http://localhost:7071/api/helloWorld1

###

POST http://localhost:7071/api/http/get-data

{
    "userId": ""
}

###

POST http://localhost:7071/api/http/reset-data

{
    "userId": ""
}

###

POST http://localhost:7071/api/http/upload-file/testData.json
Content-Type: application/json

{
    "name": "Test Data"
}

###

POST http://localhost:7071/api/orchestrators/requestApproval
Content-Type: application/json

"requestID": "1"


###

GET http://localhost:7071/api/orchestrators/raiseEventToOrchestration
Content-Type: application/json

"true"